# Generated by Django 3.0.6 on 2020-06-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tshirt_sizes', models.CharField(default='NO SIZE', max_length=4)),
            ],
        ),
    ]
