# Generated by Django 3.0.6 on 2020-05-25 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_product_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
