# Generated by Django 3.0.6 on 2020-05-27 04:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='defaultemail@fake', max_length=254)),
                ('full_name', models.CharField(blank=True, default='Skinny P', max_length=200)),
                ('password', models.CharField(default='1234', max_length=200)),
                ('password_confirm', models.CharField(default='1234', max_length=200)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
